# Generated by TAG — {{ vars.project_name }}
from flask import Flask, jsonify

app = Flask(__name__)


{% if vars.api_provider == "OpenWeatherMap" %}
# TODO: Set your OpenWeatherMap API key
OPENWEATHERMAP_API_KEY = "your-api-key-here"
{% elif vars.api_provider == "WeatherAPI" %}
# TODO: Set your WeatherAPI key
WEATHERAPI_KEY = "your-api-key-here"
{% endif %}


def get_weather(city: str) -> dict:
    """Fetch weather data for a city."""
{% if vars.api_provider == "Mock" %}
    return {
        "city": city,
        "temperature": 22.5,
        "condition": "Sunny",
        "humidity": 45,
    }
{% elif vars.api_provider == "OpenWeatherMap" %}
    import requests

    url = f"https://api.openweathermap.org/data/2.5/weather?q={city}&appid={OPENWEATHERMAP_API_KEY}&units=metric"
    resp = requests.get(url)
    resp.raise_for_status()
    data = resp.json()
    return {
        "city": city,
        "temperature": data["main"]["temp"],
        "condition": data["weather"][0]["main"],
        "humidity": data["main"]["humidity"],
    }
{% elif vars.api_provider == "WeatherAPI" %}
    import requests

    url = f"https://api.weatherapi.com/v1/current.json?key={WEATHERAPI_KEY}&q={city}"
    resp = requests.get(url)
    resp.raise_for_status()
    data = resp.json()
    return {
        "city": city,
        "temperature": data["current"]["temp_c"],
        "condition": data["current"]["condition"]["text"],
        "humidity": data["current"]["humidity"],
    }
{% endif %}


@app.route("/weather/<city>")
def weather(city: str):
    """Return weather data as JSON."""
    data = get_weather(city)
    return jsonify(data)


# ROUTES


if __name__ == "__main__":
    app.run(debug=True, port=5000)
