[tools]
go = "1.26.6"
golangci-lint = "2.10.1"
"go:golang.org/x/tools/cmd/deadcode" = "0.42.0"
"go:golang.org/x/tools/cmd/goimports" = "0.42.0"
"go:mvdan.cc/gofumpt" = "0.11.0"
"go:github.com/securego/gosec/v2/cmd/gosec" = "2.28.0"
"go:golang.org/x/vuln/cmd/govulncheck" = "1.7.0"
