// Generated by TAG — {{ vars.project_name }}
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
{% if vars.api_provider != "Mock" %}
	"io"
{% endif %}
)

// WeatherData holds weather information for a city.
type WeatherData struct {
	City        string  `json:"city"`
	Temperature float64 `json:"temperature"`
	Condition   string  `json:"condition"`
	Humidity    int     `json:"humidity"`
}

func getWeather(city string) WeatherData {
{% if vars.api_provider == "Mock" %}
	return WeatherData{
		City:        city,
		Temperature: 22.5,
		Condition:   "Sunny",
		Humidity:    45,
	}
{% elif vars.api_provider == "OpenWeatherMap" %}
	// TODO: Set your OpenWeatherMap API key
	apiKey := "your-api-key-here"
	url := fmt.Sprintf("https://api.openweathermap.org/data/2.5/weather?q=%s&appid=%s&units=metric", city, apiKey)
	resp, err := http.Get(url)
	if err != nil {
		log.Printf("error fetching weather: %v", err)
		return WeatherData{City: city}
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	var result map[string]any
	json.Unmarshal(body, &result)
	main := result["main"].(map[string]any)
	weather := result["weather"].([]any)[0].(map[string]any)
	return WeatherData{
		City:        city,
		Temperature: main["temp"].(float64),
		Condition:   weather["main"].(string),
		Humidity:    int(main["humidity"].(float64)),
	}
{% elif vars.api_provider == "WeatherAPI" %}
	// TODO: Set your WeatherAPI key
	apiKey := "your-api-key-here"
	url := fmt.Sprintf("https://api.weatherapi.com/v1/current.json?key=%s&q=%s", apiKey, city)
	resp, err := http.Get(url)
	if err != nil {
		log.Printf("error fetching weather: %v", err)
		return WeatherData{City: city}
	}
	defer resp.Body.Close()
	body, _ := io.ReadAll(resp.Body)
	var result map[string]any
	json.Unmarshal(body, &result)
	current := result["current"].(map[string]any)
	condition := current["condition"].(map[string]any)
	return WeatherData{
		City:        city,
		Temperature: current["temp_c"].(float64),
		Condition:   condition["text"].(string),
		Humidity:    int(current["humidity"].(float64)),
	}
{% endif %}
}

func weatherHandler(w http.ResponseWriter, r *http.Request) {
	city := r.PathValue("city")
	if city == "" {
		http.Error(w, "city parameter required", http.StatusBadRequest)
		return
	}
	data := getWeather(city)
	w.Header().Set("Content-Type", "application/json")
	json.NewEncoder(w).Encode(data)
}

// ROUTES

func main() {
	mux := http.NewServeMux()
	mux.HandleFunc("GET /weather/{city}", weatherHandler)

	fmt.Println("Server listening on :8080")
	log.Fatal(http.ListenAndServe(":8080", mux))
}
