#####################
##@ Lints   
#####################

lint: ## Lint tools
	go vet ./...
	@${GOBIN}/gofumpt -l -w .
	@${GOBIN}/deadcode ./...
	@${GOBIN}/golangci-lint -c .golangci.yaml run ./...

scan: ## Security scanning
	@${GOBIN}/gosec ./...
	@${GOBIN}/govulncheck ./...
